### ISSUE TITLE
[BUG] Ruin's Edge on In the Shadows Quest... Was it really intended? 

### ISSUE THREAD

**Issue by JPVilela32** [Geborgen/nordic-souls#14]
**Describe The Bug**
Ok so I think I found a bug on the mod that balances CC content: 

During the In the Shadows quest, I killed the invisible assassin on Dragonsreach and it dropped Ruins Edge instead of the Bow of Shadows... I thought... "ok that must be intentional" even when I put 0 in the MCM on the prerequisite for the bow to be the Thief's Guild questline completed. 

I carried on with the playthrough... Now on the Shivering Isles stuff, I find Ruins Edge again in the end of a dungeon... so... the Bow of Shadows not present on it's own quest is really a bug?

**Expected Behavior**

To get the proper Bow of Shadows on the corpse of the assassin at the end of the In the Shadows quest.

**List Version**

1.3.1

**Additional Context**

I didn't took screenshots of anything because I just stopped to think about it when the described quests were already completed.

**Comment by Geborgen** [comment]
The actual Bow of Shadows is obtained through the Legacy of the Dragonborn "Shattered Legacy" quest.

In 1.4, I've updated the LOTD CC patch, which should hopefully fix the Ruin's Edge issue, and patch in Extended Cut.

This is a potential fix. I completed the Bow of Shadows CC quest with console commands and the assassin didn't drop anything. Technically, the quest should be disabled, but if you manage to start it just don't do it because it's un-finishable.

I'm going to mark it as complete for now because the artifacts can be obtained correctly, but it probably requires more testing.
