### ISSUE TITLE
Poison Spell Crash

### ISSUE THREAD

**Issue by eraogon** [Geborgen/nordic-souls#8]
When ever a poison spell is cast on the player game crash
[Crash_2022_11_21_17-19-48.txt](https://github.com/Geborgen/nordic-souls/files/10061109/Crash_2022_11_21_17-19-48.txt)
[Crash_2022_11_14_17-33-14.txt](https://github.com/Geborgen/nordic-souls/files/10061110/Crash_2022_11_14_17-33-14.txt)

**Comment by Geborgen** [comment]
Not enough information & cannot reproduce on my end

**Comment by ClarSco** [comment]
I don't know exactly what's causing the Poison spell issue, but I've found something that appears to fix it.

Currently, with all the [OPTIONAL CONTENT] mods disabled, the versions of the `mpsfirebolt01.nif` and `mpsfireboltimpact01.nif` meshes with the highest priority are those from **Inferno - Fire Effects Redux**. Deleting them from that mod allows the versions from **ENB Light** to take precedence, and I've had no CTDs since when casting the Poison Spray spell.

**Comment by ClarSco** [comment]
I don't know exactly what's causing the Poison spell issue, but I've found something that appears to fix it.

Currently, with all the [OPTIONAL CONTENT] mods disabled, the versions of the `mpsfirebolt01.nif` and `mpsfireboltimpact01.nif` meshes with the highest priority are those from **Inferno - Fire Effects Redux**. Deleting them from that mod allows the versions from **ENB Light** to take precedence, and I've had no CTDs since when casting the Poison Spray spell.

**Comment by Geborgen** [comment]
(hopefully) fixed in 1.4
